---
resource_types:
- name: git-gpg
  type: docker-image
  source:
    repository: governmentpaas/git-resource

- name: s3-iam
  type: docker-image
  source:
    repository: governmentpaas/s3-resource

- name: semver-iam
  type: docker-image
  source:
    repository: governmentpaas/semver-resource

resources:
  - name: paas-cf
    type: git-gpg
    source:
      uri: https://github.com/jimconner/paas-cf.git
      branch: {{branch_name}}
      tag_filter: {{paas_cf_tag_filter}}
      commit_verification_key_ids: {{gpg_ids}}

  - name: cf-secrets
    type: s3-iam
    source:
      bucket: {{state_bucket}}
      region_name: {{aws_region}}
      versioned_file: cf-secrets.yml

  - name: cf-manifest
    type: s3-iam
    source:
      bucket: {{state_bucket}}
      region_name: {{aws_region}}
      versioned_file: cf-manifest.yml

  - name: delete-timer
    type: time
    source:
      start: 20:00 -0000
      stop: 6:00 -0000
      interval: 2h

  - name: bosh-secrets
    type: s3-iam
    source:
      bucket: {{state_bucket}}
      region_name: {{aws_region}}
      versioned_file: bosh-secrets.yml

  - name: bosh-CA
    type: s3-iam
    source:
      bucket: {{state_bucket}}
      region_name: {{aws_region}}
      versioned_file: bosh-CA.tar.gz

  - name: deployed-healthcheck
    type: s3-iam
    source:
      bucket: {{state_bucket}}
      region_name: {{aws_region}}
      versioned_file: healthcheck-deployed

jobs:
  - name: delete
    serial: true
    plan:
      - get: delete-timer
        trigger: true
      - get: bosh-secrets
      - get: paas-cf
      - get: cf-secrets
      - get: cf-manifest
      - get: bosh-CA

      - task: get-cf-cli-config
        file: paas-cf/concourse/tasks/get-cf-cli-config.yml

      - task: remove-healthcheck-db
        file: paas-cf/concourse/tasks/remove-healthcheck-db.yml

      - task: delete-deployment
        config:
          platform: linux
          inputs:
            - name: delete-timer
            - name: bosh-secrets
            - name: paas-cf
          outputs:
            - name: deployed-healthcheck
          image_resource:
            type: docker-image
            source:
              repository: governmentpaas/bosh-cli
          run:
            path: sh
            args:
              - -e
              - -c
              # The following sleep monstrosity deterministically sleeps for a
              # period of time between 0-20mins in order to prevent all our
              # deletion jobs running at the same time. See the commit message for
              # how it works.
              - |
                sum=$(echo {{deploy_env}} | md5sum);
                short=${sum:0:15};
                decimal=$((0x$short));
                sleeptime=$((${decimal##-} % 60*20));
                echo "Sleeping for $sleeptime seconds before deletion.."
                sleep $sleeptime
                ./paas-cf/concourse/scripts/bosh_login.sh {{bosh_fqdn}} bosh-secrets/bosh-secrets.yml
                bosh -n delete deployment {{deploy_env}} --force

                echo "no" > deployed-healthcheck/healthcheck-deployed
        on_success:
          put: deployed-healthcheck
          params:
            file: deployed-healthcheck/healthcheck-deployed
