resources:
  - name: delete-timer
    type: time
    source:
      start: 20:00 -0000
      stop: 21:00 -0000
      interval: 24h

jobs:
  - name: delete
    serial: true
    plan:
    - get: delete-timer
      trigger: true
    - task: delete-deployment
      config:
        inputs:
        - name: delete-timer
        image: docker:///governmentpaas/awscli
        run:
          path: sh
          args:
          - -e
          - -c
          - |
            export AWS_AVAILIABILITY_ZONE
            AWS_AVAILIABILITY_ZONE=$(curl -qs http://169.254.169.254/latest/meta-data/placement/availability-zone)
            export AWS_DEFAULT_REGION
            AWS_DEFAULT_REGION="${AWS_AVAILIABILITY_ZONE%%[a-z]}"
            export AWS_INSTANCE_ID
            AWS_INSTANCE_ID=$(curl -qs http://169.254.169.254/latest/meta-data/instance-id)

            aws ec2 terminate-instances --instance-ids ${AWS_INSTANCE_ID}
