meta:
  environment: (( grab terraform_outputs.environment ))

name: (( grab meta.environment ))
director_uuid: ~

releases:
  - name: cf
    version: 240
    url: https://bosh.io/d/github.com/cloudfoundry/cf-release?v=240
    sha1: 7dba7cc0c9c4beca699d8c876ac046890e13bb9e
  - name: diego
    version: 0.1482.0
    url: https://bosh.io/d/github.com/cloudfoundry/diego-release?v=0.1482.0
    sha1: 4d7740d58d2245b531d5fb5a3c87ab55cdd4a76b
  - name: garden-linux
    version: 0.341.0
    url: https://bosh.io/d/github.com/cloudfoundry/garden-linux-release?v=0.341.0
    sha1: 9d95512cc32d5a356928539af111dbfd16333d40
  - name: etcd
    version: 64
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/etcd-release?v=64
    sha1: 7345569e73c80681124d3cd97a3dc1be372b0381
  - name: cflinuxfs2-rootfs
    version: 1.22.0
    url: https://bosh.io/d/github.com/cloudfoundry/cflinuxfs2-rootfs-release?v=1.22.0
    sha1: bf95dfc4593e1a9f291e4bb3e50c85575483e618
  - name: paas-haproxy
    version: 0.0.4

stemcells:
  - alias: default
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: "3262.9"

update:
  canaries: 0
  max_in_flight: 2
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000
  serial: false

