---
networks:
- name: cf
  subnets:
    - range: 10.0.16.0/24
      reserved:
        - 10.0.16.2 - 10.0.16.3
      static:
        - 10.0.16.10 - 10.0.16.40
      dynamic:
        - 10.0.16.41 - 10.0.16.254
      gateway: 10.0.16.1
      dns:
        - 10.0.0.2
      cloud_properties:
        subnet: (( grab terraform_outputs.cf1_subnet_id ))
      az: z1
    - range: 10.0.17.0/24
      reserved:
        - 10.0.17.2 - 10.0.17.3
      static:
        - 10.0.17.10 - 10.0.17.40
      dynamic:
        - 10.0.17.41 - 10.0.17.254
      gateway: 10.0.17.1
      dns:
        - 10.0.0.2
      cloud_properties:
        subnet: (( grab terraform_outputs.cf2_subnet_id ))
      az: z2
    - range: 10.0.18.0/24
      reserved:
        - 10.0.18.2 - 10.0.18.3
      static:
        - 10.0.18.10 - 10.0.18.40
      dynamic:
        - 10.0.18.41 - 10.0.18.254
      gateway: 10.0.18.1
      dns:
        - 10.0.0.2
      cloud_properties:
        subnet: (( grab terraform_outputs.cf3_subnet_id ))
      az: z3

- name: cell
  subnets:
    - range: 10.0.32.0/24
      reserved:
        - 10.0.32.2 - 10.0.32.3
      gateway: 10.0.32.1
      dns:
        - 10.0.0.2
      cloud_properties:
        subnet: (( grab terraform_outputs.cell1_subnet_id ))
      az: z1
    - range: 10.0.33.0/24
      reserved:
        - 10.0.33.2 - 10.0.33.3
      gateway: 10.0.33.1
      dns:
        - 10.0.0.2
      cloud_properties:
        subnet: (( grab terraform_outputs.cell2_subnet_id ))
      az: z2
    - range: 10.0.34.0/24
      reserved:
        - 10.0.34.2 - 10.0.34.3
      gateway: 10.0.34.1
      dns:
        - 10.0.0.2
      cloud_properties:
        subnet: (( grab terraform_outputs.cell3_subnet_id ))
      az: z3
- name: router
  subnets:
    - range: 10.0.48.0/24
      reserved:
        - 10.0.48.2 - 10.0.48.3
      static:
        - 10.0.48.4 - 10.0.48.100
      gateway: 10.0.48.1
      dns:
        - 10.0.0.2
      cloud_properties:
        subnet: (( grab terraform_outputs.router1_subnet_id ))
      az: z1
    - range: 10.0.49.0/24
      reserved:
        - 10.0.49.2 - 10.0.49.3
      static:
        - 10.0.49.4 - 10.0.49.100
      gateway: 10.0.49.1
      dns:
        - 10.0.0.2
      cloud_properties:
        subnet: (( grab terraform_outputs.router2_subnet_id ))
      az: z2
