---
disk_types:
  - name: graphite_data
    disk_size: 204800
    cloud_properties: {type: gp2}

vm_types:
  - name: graphite
    network: cf
    env: (( grab meta.default_env ))
    cloud_properties:
      instance_type: t2.medium
      ephemeral_disk:
        size: 10240
        type: gp2
      elbs:
        - (( grab terraform_outputs.metrics_elb_name ))
