---
releases:
- name: datadog-agent
  sha1: e26ac31091d4577c3aec4569e740e662007b36af
  url: https://github.com/alphagov/paas-datadog-agent-boshrelease/releases/download/custom_006/datadog-agent-custom_006.tgz
  version: "custom_006"

meta:
  datadog:
    api_key: (( grab $DATADOG_API_KEY || "undefined" ))
    use_dogstatsd: false
  datadog_tags:
    environment: (( grab meta.environment || "undefined" ))
    aws_account: (( grab $AWS_ACCOUNT ))
