meta:
  aws:
    common:
      default_security_groups:
      - (( grab terraform_outputs.default_security_group ))
      region: (( grab terraform_outputs.region ))
    cloud_provider:
      credentials_source: env_or_profile
      default_key_name: (( grab terraform_outputs.bosh_ssh_key_pair_name ))
      default_security_groups: (( grab meta.aws.common.default_security_groups ))
      region: (( grab meta.aws.common.region ))
    bosh_properties:
      credentials_source: env_or_profile
      default_key_name: (( grab terraform_outputs.key_pair_name ))
      default_security_groups: (( grab meta.aws.common.default_security_groups ))
      default_iam_instance_profile: bosh-managed
      region: (( grab meta.aws.common.region ))

  bosh_private_ip: (( grab terraform_outputs.microbosh_static_private_ip ))
  bosh_public_ip: (( grab terraform_outputs.microbosh_static_public_ip ))

jobs:
- name: bosh
  properties:
    aws: (( grab meta.aws.bosh_properties ))
