---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: 2.2-slim
inputs:
  - name: paas-cf
  - name: cf-manifest
  - name: admin-creds
outputs:
  - name: test-config
run:
  path: sh
  args:
    - -e
    - -c
    - |
      export CF_MANIFEST=cf-manifest/cf-manifest.yml
      ./paas-cf/platform-tests/generate_test_config.rb \
        > test-config/config.json
