inputs:
  - name: paas-cf
  - name: bosh-secrets
  - name: cf-manifest
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/bosh-cli
platform: linux
run:
  path: sh
  args:
    - -e
    - -c
    - |
      ./paas-cf/concourse/scripts/bosh_login.sh $BOSH_FQDN bosh-secrets/bosh-secrets.yml
      bosh deployment cf-manifest/cf-manifest.yml
      bosh cck --auto
