---
platform: linux
inputs:
  - name: paas-cf
  - name: bosh-CA
  - name: config
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli
run:
  path: sh
  args:
    - -e
    - -c
    - |
      ./paas-cf/concourse/scripts/import_bosh_ca.sh
      . ./config/config.sh
      if ! curl -I -f $API_ENDPOINT/info; then
        echo "CF API unavailable. Skipping..."
        exit 0
      fi
      if ! echo | cf login -a ${API_ENDPOINT} -u ${CF_ADMIN} -p ${CF_PASS}; then
        echo "Login failed.  Skipping..."
        exit 0
      fi
      if ! cf org testers > /dev/null; then
        echo "Org 'testers' not found. Skipping..."
        exit 0
      fi
      cf target -o testers -s healthcheck
      cf delete healthcheck -f -r
      if cf services | grep -q healthcheck-db; then
        cf delete-service healthcheck-db -f
      fi
